[general]
  selection = [
    "cy49t2_alaro",
    "cy49t2_alaro_ddh",
    "cy49t2_alaro_eps",
    "cy49t2_alaro_mode_start",
    "cy49t2_alaro_target",
    "cy49t2_arome",
    "cy49t2_arome_ddh",
    "cy49t2_arome_eps",
    "cy49t2_arome_slaf",
    "cy49t2_arome_mode_start",
    "cy49t2_arome_R64",
    "cy49t2_arome_target",
    "cy49t2_harmonie_arome",
    "cy49t2_harmonie_arome_ddh",
    "cy49t2_harmonie_arome_eps",
    "cy49t2_harmonie_arome_mode_start",
    "cy49t2_harmonie_arome_R64",
    "cy49t2_harmonie_arome_target",
  ]

[general.compiler.gnu_]
  active = false
  extra = ["deode/data/config_files/modifications/submission/atos_bologna_gnu.toml"]

[general.compiler.intel_]
  active = true

[include]
  cases = "case_definitions.toml"
  macros = "macros.toml"
  modifs = "modifs_atos_bologna.toml"
