[general]
  selection = ["alaro", "arome", "harmonie_arome"]

[general.compiler.gnu_]
  active = true

[gl]
  active = true
  build_tar_path = "/scratch/project_465000527/github-actions"
  gl_hash = "53a4b71143e3b0abb2a288c69110e8740d4d08a8"
  user_binary_path = "/scratch/project_465000527/@USER@/gl_binaries"

[ial]
  active = true
  build_tar_path = "/scratch/project_465000527/github-actions"
  ial_hash = "597fe49222c84a40298322ad3e343cb7da71fa3d"
  user_binary_path = "/scratch/project_465000527/@USER@/ial_binaries"

[include]
  cases = "case_definitions.toml"

[macros.case]
  gen_macros = [{ial_hash = "ial.ial_hash"}, {user_binary_path = "ial.user_binary_path"}]
  group_macros = []
  os_macros = ["USER"]

[macros.select.default]
  gen_macros = []
  group_macros = ["modif_macros"]
  os_macros = ["USER"]

[modifs.general]
  case = "@CASE_PREFIX@@PRECISION@_@CYCLE@_@CSC@_@DOMAIN@_@YMD_START@"

[modifs.general.times]
  end = "-P1D"
  start = "-P1D"

[modifs.scheduler.ecfvars]
  case_prefix = "@USER@_@TAG@@SUBTAG@"

[modifs.submission]
  max_ecf_tasks = 10

[modifs.submission.task_exceptions.PgdFilterTownFrac.ENV]
  ECF_TRIES = 15

[modifs.submission.types.parallel.BATCH]
  WALLTIME = "#SBATCH --time=00:30:00"

[modifs.submission.types.serial.BATCH]
  MEM = "#SBATCH --mem=0GB"
  PARTITION = "#SBATCH --partition=standard"

[modifs.suite_control]
  create_static_data = true
  do_archiving = false
  do_creategrib_static = false
  do_extractsqlite = false
  do_mergesqlite = false
