[general]
  selection = [
    "cy49t2_alaro",
    "cy49t2_arome",
    "cy49t2_harmonie_arome",
    "cy49t2_harmonie_arome_R64",
    "cy49t2_arome_R64",
  ]

[general.compiler.gnu_]
  active = true
  extra = ["tactus/data/config_files/modifications/submission/atos_bologna_gnu.toml"]

[general.compiler.intel_]
  active = true

[ial]
  active = true
  build_tar_path = "/scratch/deployde330"
  ial_hash = "597fe49222c84a40298322ad3e343cb7da71fa3d"
  user_binary_path = "/scratch/@USER@/ial_binaries"

[include]
  cases = "case_definitions.toml"

[macros.case]
  gen_macros = [{ial_hash = "ial.ial_hash"}, {user_binary_path = "ial.user_binary_path"}]
  group_macros = []
  os_macros = ["USER"]

[macros.select.default]
  gen_macros = []
  group_macros = ["modif_macros"]
  os_macros = ["USER"]

[modifs.general]
  case = "@CASE_PREFIX@@PRECISION@_@CYCLE@_@CSC@_@DOMAIN@_@YMD_START@"

[modifs.general.times]
  end = "2025-09-02T00:00:00Z"
  start = "2025-09-02T00:00:00Z"

[modifs.macros.select.release_test]
  os_macros = ["PERM"]

[modifs.scheduler.ecfvars]
  case_prefix = "@TAG@@SUBTAG@"
  ecf_files = "@PERM@/tactus_ecflow/ecf_files"
  ecf_files_remotely = "@PERM@/tactus_ecflow/ecf_files"
  ecf_home = "@PERM@/tactus_ecflow/jobout"
  ecf_jobout = "@PERM@/tactus_ecflow/jobout"
  ecf_out = "@PERM@/tactus_ecflow/jobout"

[modifs.submission]
  max_ecf_tasks = 10

[modifs.suite_control]
  create_static_data = true
  do_archiving = false
  do_creategrib_static = false
  do_extractsqlite = false
  do_mergesqlite = false
